### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Prime factors not found

### ISSUE THREAD

**Issue by rama0dev** [shadowninja108/NxCertDump#7]
```
Unhandled exception. System.InvalidOperationException: Prime factors not found
   at NxCertDump.RsaUtils.RecoverRsaParameters(BigInteger n, BigInteger e, BigInteger d) in D:\a\NxCertDump\NxCertDump\NxCertDump\RsaUtils.cs:line 115
   at NxCertDump.RsaUtils.RecoverPrivateParameter(X509Certificate obj, Byte[] privateModulus) in D:\a\NxCertDump\NxCertDump\NxCertDump\RsaUtils.cs:line 18
   at NxCertDump.Program.Main(String[] args) in D:\a\NxCertDump\NxCertDump\NxCertDump\Program.cs:line 91
```

**Comment by rama0dev** [comment]
I have Mariko NX, and most likely the .bin files are different on this version, could you please update the program to support this version

**Comment by enriicsolaa** [comment]
> I have Mariko NX, and most likely the .bin files are different on this version, could you please update the program to support this version

Same problem here. Any solution?
